// Generated by CoffeeScript 2.5.1
(function() {
  var handleUpdateCombat, nextTurnIdx, wantsOnDeckNotice,
    indexOf = [].indexOf;

  wantsOnDeckNotice = function(player) {
    return true; // XXX: until we create an option for it
  };

  
  // player.getFlag("on-deck", "notifyMe")
  nextTurnIdx = function(combat, turn) {
    return (turn + 1) % combat.turns.length;
  };

  handleUpdateCombat = async function(combat, changed, options, userId) {
    var actorName, curTurn, message, nextTurn, ref, ref1, t, turns, user;
    user = game.user;
    ({
      turn: curTurn,
      turns
    } = combat);
    if (!wantsOnDeckNotice(user)) {
      return;
    }
    if (user.isGM) {
      return;
    }
    if (ref = !"turn", indexOf.call(Object.keys(changed), ref) >= 0) {
      return;
    }
    while (true) {
      nextTurn = nextTurnIdx(combat, curTurn);
      if (nextTurn === curTurn) { // all turns examined were .defeated
        return;
      }
      if ((t = turns[nextTurn]).defeated) {
        if (combat.skipDefeated) {
          continue;
        } else {
          return;
        }
      }
      if (ref1 = user.id, indexOf.call(t.players.map(function(p) {
        return p.id;
      }), ref1) >= 0) {
        actorName = t.actor.name;
        message = {
          speaker: {
            alias: "On Deck Module"
          },
          content: `Be ready to take your turn as ${actorName}.`,
          whisper: [user.id]
        };
        await ChatMessage.create(message);
      }
      return;
    }
    return void 0;
  };

  Hooks.on("updateCombat", handleUpdateCombat);

}).call(this);
