// Generated by CoffeeScript 2.5.1
(function() {
  var handleUpdateCombat, nextTurnIdx, wantsOnDeckNotice,
    indexOf = [].indexOf;

  wantsOnDeckNotice = function(player) {
    return true; // XXX: until we create an option for it
  };

  
  // player.getFlag("on-deck", "notifyMe")
  nextTurnIdx = function(combat, turn) {
    turn++;
    if (turn >= combat.turns.length) {
      turn = 0;
    }
    return turn;
  };

  handleUpdateCombat = async function(combat, changed, options, userId) {
    var actorName, curTurn, message, nextTurn, ref, t, turns, user;
    user = game.user;
    ({
      turn: curTurn,
      turns
    } = combat);
    console.log("ON-DECK: ", {arguments});
    if (!wantsOnDeckNotice(user)) {
      return;
    }
    if (!((turns != null ? turns.length : void 0) > 1)) {
      return;
    }
    if (user.isGM) {
      return;
    }
    if (indexOf.call(changed, "round") < 0 && indexOf.call(changed, "turn") < 0) {
      return;
    }
    while (true) {
      nextTurn = nextTurnIdx(curTurn);
      if (nextTurn === curTurn) {
        return;
      }
      // all turns examined were .defeated
      if ((t = turns[nextTurn]).defeated) {
        if (combat.skipDefeated) {
          continue;
        } else {
          return;
        }
      }
      if (ref = user._id, indexOf.call(t.players.map(function(p) {
        return p._id;
      }), ref) >= 0) {
        actorName = t.actor.name;
        message = {
          speaker: {
            alias: "On Deck Module"
          },
          content: `Be ready to take your turn as ${actorName}.`,
          whisper: [user._id]
        };
        await ChatMessage.create(message);
      }
      return;
    }
    return void 0;
  };

  Hooks.on("updateCombat", handleUpdateCombat);

  game.OnDeck = {handleUpdateCombat, nextTurnIdx};

}).call(this);
